package dev.weuizx.jobzi.telegram.state

/**
 * Состояния для управления многошаговыми диалогами
 */
enum class ConversationState {
    NONE,

    // Создание вакансии
    VACANCY_CREATE_TITLE,
    VACANCY_CREATE_DESCRIPTION,
    VACANCY_CREATE_LOCATION,
    VACANCY_CREATE_SALARY,
    VACANCY_CREATE_PREVIEW,
    VACANCY_CREATE_QUESTIONNAIRE_CHOICE,

    // Добавление кастомных вопросов
    QUESTION_ADD_TEXT,
    QUESTION_ADD_TYPE,
    QUESTION_ADD_REQUIRED,
    QUESTION_ADD_OPTIONS,

    // Отклик на вакансию (для соискателей)
    APPLICANT_ENTER_VACANCY_CODE,
    APPLICANT_CONFIRM_VACANCY,
    APPLICANT_ANSWERING_QUESTION,
    APPLICANT_APPLICATION_COMPLETE,

    // Управление откликами (для бизнеса)
    VIEWING_APPLICATION_DETAILS,
    VIEWING_VACANCY_APPLICATIONS,
    CHANGING_APPLICATION_STATUS,
    ADDING_APPLICATION_NOTES,

    // Суперадмин: Активация бизнеса
    SUPERADMIN_ACTIVATE_ENTER_TELEGRAM_ID,
    SUPERADMIN_ACTIVATE_ENTER_NAME,
    SUPERADMIN_ACTIVATE_ENTER_DESCRIPTION,

    // Суперадмин: Блокировка бизнеса
    SUPERADMIN_BLOCK_ENTER_ID,
    SUPERADMIN_BLOCK_ENTER_REASON,

    // Суперадмин: Разблокировка бизнеса
    SUPERADMIN_UNBLOCK_ENTER_ID,

    // Суперадмин: Управление Telegram аккаунтами
    SUPERADMIN_TELEGRAM_POOL_MENU,
    SUPERADMIN_ADD_ACCOUNT_ENTER_PHONE,
    SUPERADMIN_ADD_ACCOUNT_ENTER_API_ID,
    SUPERADMIN_ADD_ACCOUNT_ENTER_API_HASH,
    SUPERADMIN_ADD_ACCOUNT_ENTER_SESSION_NAME,
    SUPERADMIN_AUTH_SELECT_ACCOUNT,
    SUPERADMIN_AUTH_ENTER_CODE,
    SUPERADMIN_AUTH_ENTER_PASSWORD,
    SUPERADMIN_DELETE_ACCOUNT_SELECT,
    SUPERADMIN_DELETE_ACCOUNT_CONFIRM,

    // Бизнес: Просмотр и управление вакансией
    VIEWING_VACANCY_DETAILS,
    VACANCY_ACTION_MENU,

    // Бизнес: Редактирование вакансии
    VACANCY_EDIT_CHOOSE_FIELD,
    VACANCY_EDIT_INPUT_VALUE,
    VACANCY_CHANGE_STATUS,
    VACANCY_DELETE_CONFIRM,

    // Бизнес: Управление анкетой/вопросами
    QUESTIONNAIRE_MANAGEMENT_MENU,
    QUESTIONNAIRE_VIEW_LIST,
    QUESTIONNAIRE_DELETE_ENTER_NUMBER,
    QUESTIONNAIRE_EDIT_CHOOSE_QUESTION,
    QUESTIONNAIRE_EDIT_CHOOSE_FIELD,
    QUESTIONNAIRE_EDIT_INPUT_VALUE,

    // Бизнес: Управление рекламными рассылками
    BROADCAST_MENU,
    BROADCAST_CAMPAIGN_CREATE_TITLE,
    BROADCAST_CAMPAIGN_CREATE_MESSAGE,
    BROADCAST_CAMPAIGN_PREVIEW,
    BROADCAST_CAMPAIGN_CONFIRM_SEND,
    BROADCAST_CHANNEL_ADD_ID,
    BROADCAST_CHANNEL_MANAGEMENT,
    BROADCAST_CHANNEL_DELETE_CONFIRM,
    BROADCAST_CAMPAIGNS_LIST,
    BROADCAST_CAMPAIGN_VIEW_DETAILS,
    BROADCAST_CAMPAIGN_SCHEDULE_TYPE,
    BROADCAST_CAMPAIGN_SCHEDULE_TIME,
    BROADCAST_CAMPAIGN_EDIT_SCHEDULE
}